title: "Pranav Joshi"
email: "pranavjoshi2107@gmail.com"
description: >-
  Researcher in Quantum Computing and Machine Learning.
  Interested in the study of intelligent systems,
  and the intersection of machine learning and physics. Also a pianist.
baseurl: "" # do not change this
url: "https://pranaj21.github.io"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

# Enable these plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Social links
author:
  name: "Pranav Joshi"
  # optional, replace with your photo
  bio: "Quantum Computing | Machine Learning | Amateur Pianist"
  location: "Pune, MH"
  email: "pranavjoshi2107@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/PranavJ21"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/PranavJ21"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=JQhocz4AAAAJ"

# Navigation bar
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Navigation menu
collections:
  pages:
    output: true

# Optional: Customize logo, favicon, etc.

