title: "Pranav Joshi"
email: "your@email.com"
description: >-
  Researcher in Quantum Computing and Machine Learning.
  Interested in the study of intelligent systems,
  and the intersection of machine learning and physics. Also a pianist.
baseurl: "" # do not change this
url: "https://pranav.github.io"

theme: minimal-mistakes-jekyll

# Enable these plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Social links
author:
  name: "Pranav Joshi"
  avatar: "/assets/images/avatar.png" # optional, replace with your photo
  bio: "Quantum ML | Climate Informatics | Pianist"
  location: "India"
  email: "your@email.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/PranavJ21"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/PranavJ21"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=JQhocz4AAAAJ"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:pranavjoshi2107@gmail.com"

# Navigation bar
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Navigation menu
collections:
  pages:
    output: true

# Optional: Customize logo, favicon, etc.

